filetype indent plugin on 
syntax on 
set hls
set ignorecase 
set smartcase 
set backspace=indent,eol,start 
set nostartofline 
set autoindent 
set ruler 
set laststatus=2
set confirm 
set number 
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab 
set scrolloff=5 
set sidescrolloff=5 
set noerrorbells 
set novisualbell 
set t_vb= 
set tm=500 
set wildmenu 
set showmatch 
set history=700
set mouse=a
